// 
// Decompiled by Procyon v0.5.29
// 

package com.amazon.device.ads;

enum Metrics$MetricType
{
    AAX_CONFIG_DOWNLOAD_FAILED("AAX_CONFIG_DOWNLOAD_FAILED", 43, "acf"), 
    AAX_CONFIG_DOWNLOAD_LATENCY("AAX_CONFIG_DOWNLOAD_LATENCY", 42, "acl"), 
    AAX_LATENCY_GET_AD("AAX_LATENCY_GET_AD", 17, "al"), 
    ADLAYOUT_HEIGHT_ZERO("ADLAYOUT_HEIGHT_ZERO", 29, "ahz"), 
    AD_COUNTER_AUTO_AD_SIZE("AD_COUNTER_AUTO_AD_SIZE", 27, "aas"), 
    AD_COUNTER_FAILED_DUE_TO_NO_RETRY("AD_COUNTER_FAILED_DUE_TO_NO_RETRY", 25, "nrtf"), 
    AD_COUNTER_IDENTIFIED_DEVICE("AD_COUNTER_IDENTIFIED_DEVICE", 21, "id"), 
    AD_COUNTER_PARENT_VIEW_MISSING("AD_COUNTER_PARENT_VIEW_MISSING", 28, "pvm"), 
    AD_COUNTER_RENDERING_FATAL("AD_COUNTER_RENDERING_FATAL", 22, "rf", true), 
    AD_FAILED_INVALID_AUTO_AD_SIZE("AD_FAILED_INVALID_AUTO_AD_SIZE", 34, "faas"), 
    AD_FAILED_LAYOUT_NOT_RUN("AD_FAILED_LAYOUT_NOT_RUN", 33, "flnr"), 
    AD_FAILED_NULL_LAYOUT_PARAMS("AD_FAILED_NULL_LAYOUT_PARAMS", 32, "fnlp"), 
    AD_FAILED_UNKNOWN_WEBVIEW_ISSUE("AD_FAILED_UNKNOWN_WEBVIEW_ISSUE", 31, "fuwi"), 
    AD_IS_INTERSTITIAL("AD_IS_INTERSTITIAL", 49, "i"), 
    AD_LATENCY_RENDER("AD_LATENCY_RENDER", 23, "rl", true), 
    AD_LATENCY_RENDER_FAILED("AD_LATENCY_RENDER_FAILED", 24, "rlf", true), 
    AD_LATENCY_TOTAL("AD_LATENCY_TOTAL", 0, "tl", true), 
    AD_LATENCY_TOTAL_FAILURE("AD_LATENCY_TOTAL_FAILURE", 2, "tfl", true), 
    AD_LATENCY_TOTAL_SUCCESS("AD_LATENCY_TOTAL_SUCCESS", 1, "tsl", true), 
    AD_LOADED_TO_AD_SHOW_TIME("AD_LOADED_TO_AD_SHOW_TIME", 14, "alast"), 
    AD_LOAD_FAILED("AD_LOAD_FAILED", 18, "lf"), 
    AD_LOAD_FAILED_ON_AAX_CALL_TIMEOUT("AD_LOAD_FAILED_ON_AAX_CALL_TIMEOUT", 19, "lfat"), 
    AD_LOAD_FAILED_ON_PRERENDERING_TIMEOUT("AD_LOAD_FAILED_ON_PRERENDERING_TIMEOUT", 20, "lfpt"), 
    AD_LOAD_LATENCY_AAX_GET_AD_END_TO_FETCH_THREAD_END("AD_LOAD_LATENCY_AAX_GET_AD_END_TO_FETCH_THREAD_END", 6, "laefel"), 
    AD_LOAD_LATENCY_CREATE_AAX_GET_AD_URL("AD_LOAD_LATENCY_CREATE_AAX_GET_AD_URL", 10, "lcaul"), 
    AD_LOAD_LATENCY_FETCH_THREAD_SPIN_UP("AD_LOAD_LATENCY_FETCH_THREAD_SPIN_UP", 4, "lfsul"), 
    AD_LOAD_LATENCY_FETCH_THREAD_START_TO_AAX_GET_AD_START("AD_LOAD_LATENCY_FETCH_THREAD_START_TO_AAX_GET_AD_START", 5, "lfsasl"), 
    AD_LOAD_LATENCY_FINALIZE_FETCH_SPIN_UP("AD_LOAD_LATENCY_FINALIZE_FETCH_SPIN_UP", 7, "lffsul"), 
    AD_LOAD_LATENCY_FINALIZE_FETCH_START_TO_FAILURE("AD_LOAD_LATENCY_FINALIZE_FETCH_START_TO_FAILURE", 9, "lffsfl", true), 
    AD_LOAD_LATENCY_FINALIZE_FETCH_START_TO_RENDER_START("AD_LOAD_LATENCY_FINALIZE_FETCH_START_TO_RENDER_START", 8, "lffsrsl", true), 
    AD_LOAD_LATENCY_LOADAD_TO_FETCH_THREAD_REQUEST_START("AD_LOAD_LATENCY_LOADAD_TO_FETCH_THREAD_REQUEST_START", 3, "llfsl", true), 
    AD_NO_RETRY_TTL_RECEIVED("AD_NO_RETRY_TTL_RECEIVED", 26, "nrtr"), 
    AD_SHOW_DURATION("AD_SHOW_DURATION", 16, "asd"), 
    AD_SHOW_LATENCY("AD_SHOW_LATENCY", 15, "lsa"), 
    ASSETS_CREATED_LATENCY("ASSETS_CREATED_LATENCY", 11, "lacl"), 
    ASSETS_ENSURED_LATENCY("ASSETS_ENSURED_LATENCY", 12, "lael"), 
    ASSETS_FAILED("ASSETS_FAILED", 13, "af"), 
    CARRIER_NAME("CARRIER_NAME", 47, "car"), 
    CONFIG_DOWNLOAD_ERROR("CONFIG_DOWNLOAD_ERROR", 39, "cde"), 
    CONFIG_DOWNLOAD_LATENCY("CONFIG_DOWNLOAD_LATENCY", 40, "cdt"), 
    CONFIG_PARSE_ERROR("CONFIG_PARSE_ERROR", 41, "cpe"), 
    CONNECTION_TYPE("CONNECTION_TYPE", 48, "ct"), 
    CUSTOM_RENDER_HANDLED("CUSTOM_RENDER_HANDLED", 44, "crh"), 
    SIS_COUNTER_IDENTIFIED_DEVICE_CHANGED("SIS_COUNTER_IDENTIFIED_DEVICE_CHANGED", 35, "sid"), 
    SIS_LATENCY_REGISTER("SIS_LATENCY_REGISTER", 36, "srl"), 
    SIS_LATENCY_REGISTER_EVENT("SIS_LATENCY_REGISTER_EVENT", 38, "srel"), 
    SIS_LATENCY_UPDATE_DEVICE_INFO("SIS_LATENCY_UPDATE_DEVICE_INFO", 37, "sul"), 
    TLS_ENABLED("TLS_ENABLED", 45, "tls"), 
    VIEWPORT_SCALE("VIEWPORT_SCALE", 30, "vs"), 
    WIFI_PRESENT("WIFI_PRESENT", 46, "wifi");
    
    private final String aaxName;
    private final boolean isAdTypeSpecific;
    
    private Metrics$MetricType(final String s, final int n, final String s2) {
        this(s, n, s2, false);
    }
    
    private Metrics$MetricType(final String name, final int ordinal, final String aaxName, final boolean isAdTypeSpecific) {
        this.aaxName = aaxName;
        this.isAdTypeSpecific = isAdTypeSpecific;
    }
    
    public final String getAaxName() {
        return this.aaxName;
    }
    
    public final boolean isAdTypeSpecific() {
        return this.isAdTypeSpecific;
    }
}
